Feature/8 implement chat entities methods
is-tech-y24-1/Do-Svyazi.User pull request #18
Opened 2022-05-29 17:30 UTC by KotDimos

В базовый чат добавлено:
Добавление/Удаление user
Добавление/Удаление role

Получение user
Получение количества users
Получение List<user> по их роли 
Изменение имени чата 
Изменение описания чата

2022-05-29 17:36 UTC, lipa44 commented
То же самое, что у исы..

Пр надо делаnь не в master, а в dev

2022-05-29 17:59 UTC, lipa44 requested changes
Этот парень был из тех, кто просто любит жить...

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
>      public List<Role> Roles { get; init; } = new ();
Сделай `IReadOnlyCollection<>` и уже в самих классах потом сделаешь private `List<>`

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        Name = name ?? throw new NullReferenceException("Name chat is null");
`NullReferenceException` - это когда ты обращаешься к null _(например `name.Length` когда name - null)_, если мы работаем со строками, тут должен быть `ArgumentNullException` и проверка **строки** на то что она пустая, а не только на то что это `null`.

```suggestion
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentNullException("Chat name to set is null");

        Name = name;
```

Ну и желательно чуть правильнее писать сообщение ошибки: Chat name is null || Chat name to set is null

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        Description = description ?? throw new NullReferenceException("Name chat is null");
тож самое

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        return Users.Where(user => user.Role.Name == role.Name).ToList();
Зачем сравнивать по Name?

Лучше перегрузить сравнение Role и сравнивать по `.Equals()`

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            return user;
Это шо? Сделай `.SingleOrDefault()` и кинь ошибку если не нашлось

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        return new ChatUser();
вот так делать вообще ни в коем случае не надо

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    }
Смысла этого метода вообще не понял, можно же вытащить юзеров и тыкнуть Count.

Ну или на крайняк сделать переменную, которая возвращает Users.Count, но точно не метод

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new NullReferenceException("ChatUser is null");
Опять ArgumentNullException + проверка на то что юзер уже не существует

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new NullReferenceException("ChatUser is null");
Опять ArgumentNullException + IEnumerable.Remove() возвращает bool - удалось удалить или нет, так что тут можно без проверки того, что юзер существует, но с проверкой того, что это не нул.

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new NullReferenceException("Role is null");
Опять ArgumentNullException + проверка на то что роль уже не существует

2022-05-29 17:59 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new NullReferenceException("Role is null");
Аналогично удалению юзера

2022-05-29 18:03 UTC, lipa44 commented
> В базовый чат добавлено: Добавление/Удаление user Добавление/Удаление role
> 
> Получение user Получение количества users Получение List по их роли Изменение имени чата Изменение описания чата
> 
> Теперь вопросы:
> 
> 1. что можно/нужно добавить из методов
> 2. В сохранённых сообщениях, по идее надо сделать какой-то синглтон, чтобы мы могли создавать только один чат, только вопрос как это будет организованно на другой стороне
> 3. В лс, должна быть проверка что всего два пользователя, как это лучше реализовать, если уже 2 пользователя - посылать нафиг?

1. На подумать, такска-то как раз на то, чтобы это придумать и реализовать))
2. Паттерны не особо ложатся на работу с БД
3. **Возможно**, при добавлении пользователя проверить, что их не больше чем можно.

2022-05-29 18:15 UTC, lipa44 commented
Чтобы окончательно тебя задушить: [в соглашении именования коммитов](https://www.conventionalcommits.org/en/v1.0.0/) нету add :)

> Это просто саджест

2022-05-29 18:46 UTC, lipa44 commented
Сделай ещё пж конструктор(ы) у чата в базовом классе с параметрами.

2022-05-29 20:45 UTC, lipa44 requested changes
Ещё убери лишние слова Chat в названиях методов и перепиши сообщения эксепшенов чтобы они давали больше информации (пример я накинул)

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        Description = description;
проверки IsEmptyOrWhitespace

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    public IReadOnlyCollection<Role> Roles => _roles.AsReadOnly();
Зачем `AsReadOnly()`? Оно спокойно само кастится к ридонли.

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new ArgumentNullException("Chat name to set is null");
1. В ArgumentNullException первым параметром идёт имя того, что null, а вторым - `сообщение`

```suggestion
        if (string.IsNullOrWhiteSpace(description))
            throw new ArgumentNullException(nameof(description), "Chat description to set is null");
```

2. Chat name?)

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new ArgumentNullException("Chat name to set is null");
```suggestion
        if (string.IsNullOrWhiteSpace(name))
            throw new ArgumentNullException(nameof(name), "Chat name to set is null");
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    public virtual void ChangeNameChat(string name)
Не думаю, что `ChangeNameChat` и `ChangeDescriptionChat` нужно делать виртуальными, логика-то в разных чатах меняться не будет у этих методов

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    public List<ChatUser> GetChatUsersRole(Role role)
```suggestion
    public IReadOnlyCollection<ChatUser> GetChatUsersRole(Role role)
        => Users.Where(user => user.Role.Equals(role)).ToList();
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    }
```suggestion
    public ChatUser GetChatUser(string nickName) =>
        Users.SingleOrDefault(user => user.NickName == nickName)
        ?? throw new Do_Svyazi_User_NotFoundException($"User with nickName {nickName} not found in chat {Name}");
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +        if (Users.Contains(chatUser))
`Contains` вызовет базовый `.Equals()` у класса `ChatUser`, и если он не перегружен (а он не перегружен), то будет плохо

Сделай приватный метод IsUserExist() и реализуй там логику поиска, нужно будет ещё перегрузить у юзера Equals

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +            throw new Do_Svyazi_User_InnerLogicException("This user already exists");
Какой This? Ты не даёшь никакой инфы о том, что это за юзер
```suggestion
            throw new Do_Svyazi_User_InnerLogicException($"User {chatUser.nickName} already exists in chat {Name}");
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    }
Этот метод должны реализовывать классы-наследники, тут не должно быть реализации, т.к. она будет меняться в зависимости от бизнес-логики каждого типа чатов
```suggestion
    public abstract void RemoveChatUser(ChatUser chatUser);
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    }
Этот метод должны реализовывать классы-наследники, тут не должно быть реализации, т.к. она будет меняться в зависимости от бизнес-логики каждого типа чатов
```suggestion
    public abstract void AddChatUser(ChatUser chatUser);
```

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    public virtual void AddRole(Role role)
Можно убрать плашку виртуальности (так же как и во всех остальных методах), т.к. эти методы не требуют особой бизнес-логики и будут просто наследоваться остальными типами чатов.

2022-05-29 20:45 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Roles/Role.cs
> +        Name == role.Name;
Я в процессе решения конфликтов немного поменял вот это место:

1) Второй Equals, который ты вызываешь внутри перегруженного, должен быть приватным
2) Приводить к инту каждый ActionOption нет смысла, можно сравнить по имени и айдишнику чата, учитывая что внутри чата не может быть несколько ролей с одинаковым именем
3) Вместо `!=` используй `is not` - != не на хайпе :)

2022-05-29 21:20 UTC, lipa44 commented
#8 Issue

2022-05-30 05:02 UTC, KotDimos commented on Domain/Do-Svyazi.User.Domain/Chats/Chat.cs
> +    public virtual void ChangeNameChat(string name)
Нет, она будет меняться, личные сообщения мы в теории не сможем поменять (если как вариант в телеге что каждый может поменять для себя), и сохранённые сообщения, там вообще невозможно

2022-05-30 16:21 UTC, lipa44 requested changes
Не закидывай пж когда просто сделаешь все изменения, посмотри на код и подумай, устраивает ли он тебя самого

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
> +            ChatId = Id,
Сделай всё-таки чат тут вместо ChatId

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
>      public override void AddUser(ChatUser chatUser)
По-моему, в чат приходит MessengerUser, и уже при добавлении получается ChatUser
```suggestion
    public override void AddUser(MessengerUser user)
```

Аналогично в остальных методах

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
> +        Users.Add(chatUser);
1. Сделай метод который из юзера делает ChatUser (можно в базовом классе)
2. Сообщения ошибок - я уже говорил об этом.

```suggestion
        if (user is null)
            throw new ArgumentNullException(nameof(user), "User {user.NickName} to add in chat {Name} is null");

        if (Users.Contains(chatUser))
            throw new Do_Svyazi_User_InnerLogicException($"User {user.NickName} already exists in chat {Name}");
        
        var chatUser = CreateChatUser(user);
        Users.Add(chatUser);
```

Аналогично в остальных методах

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/Channel.cs
>      public override void RemoveUser(ChatUser chatUser)
MessengerUser

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/GroupChat.cs
> +        };
метод создания юзера чтобы каждый раз одно и то же не писать

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
> +        if (Users.Count != 1)
магическое число?

либо сделай поле у базового класса где ты будешь хранить максимальное число участников, либо просто сделай константу в каждом из типов чата (лучше в базовом)

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
> +        if (Users.Count != 2)
магическое число?

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
> +        throw new Do_Svyazi_User_BusinessLogicException($"Error added role in chat {Name}");
Error added?)

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/PersonalChat.cs
> +            throw new Do_Svyazi_User_InnerLogicException($"Error removed user {chatUser.User.Name} in chat {Name}");
Error removed?)

```suggestion
            throw new Do_Svyazi_User_InnerLogicException($"Chat {Name} does not support adding users");
```

Аналогично остальные

2022-05-30 16:21 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Chats/SavedMessages.cs
> +        };
выше написал

2022-05-31 12:24 UTC, lipa44 reviewed
Вроде ок, только нейминг...

Щас сделаю коммит на нейминг и сможешь мержить

2022-05-31 14:18 UTC, merged