feat: DeleteUser operation
is-tech-y24-1/Do-Svyazi.User pull request #19
Opened 2022-05-30 11:23 UTC by iskander-faggod

# 3

2022-05-31 14:33 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/DeleteUser.cs
> +            _context.Users.Remove(foundedUser);
желательно настроить поведение при удалении (EF), но пока что необязательно

2022-05-31 14:34 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsByUserId.cs
> +            if (foundedUser is null)
кекв

<img width="1310" alt="image" src="https://user-images.githubusercontent.com/82240296/171199486-187592eb-feac-4917-a320-be51ddca690b.png">

2022-05-31 14:34 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsIdByUserId.cs
> +            if (foundedUser is null)
same

2022-05-31 14:35 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsIdByUserId.cs
> +            if (foundedUser is null)
?? проверку на нул можно вставить как ты до этого делал

2022-05-31 14:38 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    [HttpGet("GetUser")]
верю что контроллеры ты сделал норм, только нейминг `GetUserById` вместо `GetUser` и тп

2022-05-31 15:48 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/DeleteUser.cs
> +            _context.Users.Remove(foundedUser);
ну она уже есть, просто тут вопрос в том, готовы ли мы разом настроить весь EF, если можно потихоньку добавлять какие-то конфиги а в итоговом всё это допилить окончательно

2022-05-31 16:39 UTC, iskander-faggod commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    }
пушто в первом мы сущности возвращаем, а во втором айдишники

2022-05-31 16:40 UTC, iskander-faggod commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    [HttpPost("AddChatToUser")]
я хочу чтобы было очев че они делают, если у меня контроллеры никак не меняют логику сервиса, то почему я не могу назвать их также как метод сервиса?)

2022-05-31 18:07 UTC, lipa44 commented
Сейчас будет лучшее ревью в твоей жизни (и в моей)

2022-05-31 18:31 UTC, lipa44 requested changes
Воркаем

2022-05-31 18:31 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsByUserId.cs
> +            return messengerUser.Chats.Select(chat => _mapper.Map<MessengerChatDto>(chat)).ToList();
Можно сразу лист через маппер закупорить

2022-05-31 18:31 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsByUserId.cs
> +            return messengerUser.Chats.Select(chat => _mapper.Map<MessengerChatDto>(chat)).ToList();
Без селекта

2022-05-31 18:31 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetAllChatsIdByUserId.cs
> +    public record Command(Guid userId) : IRequest<List<Guid>>;
IReadOnlyList/IReadOnlyCollection

2022-05-31 18:31 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/GetUser.cs
> +    public record Command(Guid userId) : IRequest<Guid>, IRequest<MessengerUser>;
IRequest<Guid, MessengerUser> тебе чем не понравился?

2022-05-31 18:31 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/Do-Svyazi.User.Application.csproj
>      </PropertyGroup>
Ревертни ты уже изменения. Ctrl+alt+c

2022-05-31 18:31 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    }
Ты в обоих одно и то же возвращаешь….

2022-05-31 18:31 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    public async Task<ActionResult<MessengerUser>> GetAllChatsByUserId(Guid userId)
Возвращаешь юзеров вместо чатов?

2022-05-31 18:31 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    [HttpPost("AddChatToUser")]
Я те говорю в вместо строки напиши nameof))))

2022-06-01 12:40 UTC, iskander-faggod commented on Presentation/Do-Svyazi.User.Web.Controllers/UserController.cs
> +    }
нет, в первом лист гуидов, во втором лист дтошек

2022-06-01 17:06 UTC, iskander-faggod commented
#4

2022-06-01 17:17 UTC, lipa44 requested changes

2022-06-01 17:17 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/AddUser.cs
> +        private async Task<bool> UserExist(string nickName)
```suggestion
        private async Task<bool> IsUserExist(string nickName)
```

2022-06-01 17:17 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/AddUser.cs
> +        private async Task<bool> UserExist(string nickName)
P.S. такой нейминг сори

2022-06-01 17:17 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Users/Commands/AddUser.cs
> +            return foundUser is null;
`is not null` может?
```suggestion
            MessengerUser? foundUser = await _context.Users.FindAsync(nickName);
            return foundUser is not null;
```

если у тебя нашёлся юзер и ты проверил is null, то он тебе вернёт false

а метод называется UserExist (IsUserExist) -> юзер есть но он тебе вернул false

2022-06-01 17:36 UTC, lipa44 commented
Да

2022-06-01 17:37 UTC, lipa44 approved these changes
Да!

2022-06-01 18:05 UTC, merged