feat/ CRUD for Roles
is-tech-y24-1/Do-Svyazi.User pull request #29
Opened 2022-06-04 09:28 UTC by iskander-faggod

## Вкратце опиши свои изменения

1. Я сделал CRUD методы для Roles

## Номер выполненной ишуи

Closing issue #6

2022-06-08 16:43 UTC, lipa44 requested changes
Нормас, пофикси ток то что я написал и посмотри, чтобы во всех эксепшенах были айдишники

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeChatRole.cs
> +public static class ChangeChatRole
```suggestion
public static class ChangeUserRoleInChat
```

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeChatRole.cs
> +                throw new Do_Svyazi_User_BusinessLogicException("Role to set is null");
выведи пж айдишники чата и юзера

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeChatRole.cs
> +            await _context.SaveChangesAsync(cancellationToken);
какие изменения ты сохраняешь? Чтобы что-то сохранить, нужно сначала что-то апдейтнуть

тебе надо создать эту роль и добавить в базу данных + надо обновить её у юзера в базе данных

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeRoleForUserById.cs
> +            };
роль должна быть привязана к чату, иначе оно работать не будет

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Queries/GetRoleByUserId.cs
> +            return chatUser.Role;
ты же добавил таблицу ролей в DbContext - поидее же можно найти роль с нужным чат и юзер айдишниками

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/DbContexts/IDbContext.cs
> +    public DbSet<Role> Role { get; init; }
```suggestion
    public DbSet<Role> Roles { get; init; }
```

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Dtos/Do-Svyazi.User.Dtos.csproj
>      </ItemGroup>
<img width="212" alt="image" src="https://user-images.githubusercontent.com/82240296/172671045-e600a7b2-041b-40ea-ac30-b3ee09f30967.png">

2022-06-08 16:43 UTC, lipa44 commented on Application/Do-Svyazi.User.Dtos/Roles/RoleDto.cs
> +public class RoleDto
```suggestion
public record RoleDto
```

и все дто поменяй на рекорд - это улучшит перф :)

2022-06-08 16:43 UTC, lipa44 commented on Infrastructure/Do-Svyazi.User.DataAccess/DoSvaziDbContext.cs
> +    public DbSet<Role> Role { get; init; }
```suggestion
    public DbSet<Role> Roles { get; init; }
```

2022-06-10 21:22 UTC, lipa44 requested changes
норм, пофикси комменты и заливай

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeRoleForUserById.cs
> +            await _context.SaveChangesAsync(cancellationToken);
Если ты создал новую роль, тебе нужно её добавить в базу.

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeUserRoleInChat.cs
> +            {
почему эта проверка тут а не в методе `ChangeUserRole`?

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeUserRoleInChat.cs
> +            _context.Roles.Add(_mapper.Map<Role>(request.newRole));
Найти просто чатЮзера и поставить ему роль кажется более правильным, чем искать чат и юзера.

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeUserRoleInChat.cs
> +            return chatAndUserId;
Можно просто Unit

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/CreateRoleForChat.cs
> +        }
это тоже должно быть поидее внутри метода AddRole чата

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/CreateRoleForChat.cs
> +            try
убери try/catch пж

2022-06-10 21:22 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/CreateRoleForChat.cs
> +        }
`.Any()` ?)

2022-06-10 21:23 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Roles/Commands/ChangeUserRoleInChat.cs
> +            return chatAndUserId;
я имел ввиду вывести в сообщении эксепшена)

2022-06-11 08:53 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/RoleController.cs
> +    public RoleController(IMediator mediator) => _mediator = mediator;
### 
```suggestion
    public RolesController(IMediator mediator) => _mediator = mediator;
```

2022-06-11 12:26 UTC, lipa44 approved these changes
Верю!

2022-06-11 12:27 UTC, iskander-faggod commented
![image](https://user-images.githubusercontent.com/60395869/173187925-100e6a2e-1617-45e9-8747-a2dd647f1058.png)

2022-06-11 12:28 UTC, merged