feat: auth
is-tech-y24-1/Do-Svyazi.User pull request #34
Opened 2022-06-12 11:21 UTC by iskander-faggod

## Вкратце опиши свои изменения

1. Начал делать авторизацию/аутентификацию

## Номер выполненной ишуи

Closing issue #10

2022-06-12 17:58 UTC, lipa44 commented on Infrastructure/Do-Svyazi.User.DataAccess/ApplicationDbContext.cs
> +                .Ignore(u => u.PhoneNumber);
выглядит неочент

2022-06-12 20:38 UTC, lipa44 requested changes

2022-06-12 20:38 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/AuthenticateController.cs
> +        public async Task<IActionResult> Login([FromBody] LoginModel model)
шаблонизируй возвращаемый результат

2022-06-12 20:38 UTC, lipa44 commented on Domain/Do-Svyazi.User.Domain/Authenticate/RegisterModel.cs
> +public record RegisterModel
добавь почту что-ли в модельку и поддержи это минимально

2022-06-12 20:38 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/RegisterAdmin.cs
> +                await _roleManager.CreateAsync(new MessageIdentityRole(MessageIdentityRole.User));
а ты это засинкал с нашей системой или как это будет работать? надо будет одновременно вызвать эту ручку и ручку создания чата?

2022-06-12 20:38 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/Register.cs
> +        }
Зачем тут конфигурация?

2022-06-12 20:38 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/RegisterAdmin.cs
> +            }
два раза проверка на наличие роли админа?

2022-06-14 13:28 UTC, iskander-faggod commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/RegisterAdmin.cs
> +                await _roleManager.CreateAsync(new MessageIdentityRole(MessageIdentityRole.User));
не синькал, пока работает так, что мы создаем юзера и чаты отдельно

2022-06-14 18:35 UTC, lipa44 approved these changes

2022-06-14 18:35 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/Login.cs
> +                expires: DateTime.Now.AddHours(3),
вынеси тоже в конфигурацию пж

2022-06-14 18:35 UTC, lipa44 commented on Application/Do-Svyazi.User.Application/CQRS/Authenticate/RegisterAdmin.cs
> +                await _userManager.AddToRoleAsync(user, MessageIdentityRole.User);
```suggestion
            if (!await _roleManager.RoleExistsAsync(MessageIdentityRole.Admin))
            {
                await _roleManager.CreateAsync(new MessageIdentityRole(MessageIdentityRole.Admin));
                await _userManager.AddToRoleAsync(user, MessageIdentityRole.Admin);
             }

            if (!await _roleManager.RoleExistsAsync(MessageIdentityRole.User))
            {
                await _roleManager.CreateAsync(new MessageIdentityRole(MessageIdentityRole.User));
                await _userManager.AddToRoleAsync(user, MessageIdentityRole.User);
             }
```

Мб смержить их?

2022-06-14 18:35 UTC, lipa44 commented on Presentation/Do-Svyazi.User.Web.Controllers/AuthenticateController.cs
> +    [ApiController]
По-хорошему в этом файле навесить статус-коды для эндпоинтов, тк в авторизации-то они точно важны (200, 403 и тд)

Можно это в отдельную таску, конечно, засунуть :)

2022-06-15 16:23 UTC, merged